import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newContext({ viewport: { width: 1280, height: 850 } }).then(c=>c.newPage());
const errs=[]; page.on('pageerror',e=>errs.push('PAGEERR: '+e.message)); page.on('console',m=>{if(m.type()==='error')errs.push('CONSOLE: '+m.text());});
await page.goto('http://localhost:3000/', { waitUntil:'networkidle' });
await page.waitForTimeout(1500);
const html = await page.evaluate(() => document.querySelector('#root')?.innerHTML.slice(0,400) || 'NO ROOT');
const hasNav = await page.evaluate(() => !!document.querySelector('.navbar, button.nav-group-btn'));
console.log('hasNav:', hasNav);
console.log('root head:', html);
console.log('ERRORS:', errs.slice(0,10).join('\n'));
await browser.close();
